version: '3.8'

networks:
  automation-net:
    driver: bridge

services:
  playwright-mcp:
    build:
      context: .
      dockerfile: mcp-server.Dockerfile
    container_name: mcp-server # Explicit hostname for backend connection
    # command: is now defined in the Dockerfile CMD
    networks:
      - automation-net
    healthcheck:
      # Guessing pnpm start runs a node process. May need adjustment.
      test: ["CMD", "pgrep", "-f", "node"] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Allow more time for build steps if needed on first run
    # Note: Port 59985 is internal to the Docker network, not exposed to host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Assuming standard Dockerfile name
    container_name: backend-service
    ports:
      - "3000:3000" # Expose backend port to host
    environment:
      # Backend connects to MCP server via its container name on the Docker network
      # - MCP_SERVER_WS=ws://mcp-server:59985/ # Use official default WS port 59985 and path /
      - MCP_SERVER_SSE_URL=http://mcp-server:59985/sse # Use SSE endpoint
      # Pass the OpenAI API Key from the .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Add any other necessary backend environment variables here
      # - NODE_ENV=development
    networks:
      - automation-net
    depends_on:
      playwright-mcp:
        condition: service_healthy

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile # Assuming standard Dockerfile name
    container_name: ui-service
    ports:
      - "5173:5173" # Expose UI port to host (as requested)
    environment:
      # Set the base URL for the browser to access the backend API
      - VITE_API_BASE_URL=http://localhost:3000
      # Add any other necessary UI environment variables here
      # - NODE_ENV=development
    networks:
      - automation-net
    depends_on:
      backend:
        condition: service_started
 