name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0, v2.3.4, etc.

jobs:
  build-and-publish:
    name: Build and Publish Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed for actions/checkout
      packages: write # Needed to push packages (Docker images) to GHCR
      id-token: write # Optional: if using OIDC for authentication elsewhere

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Image name format: ghcr.io/OWNER/REPO
          # Uses Git tag as Docker tag, also tags as 'latest' if it's the default branch tag
          tags: |
            type=semver,pattern={{version}}
            type=sha # Add git sha tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the Dockerfile at the root
          file: ./Dockerfile
          push: true # Actually push the image
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Enable GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max 